const DEADLINE=new Date('2026-08-11T23:59:59');
const defaultTasks=[
{id:1,title:'Completar Datos Maestros',detail:'Razón social, unidad, ubicación, responsables y cultivo.',owner:'Dirección',priority:'critical',status:'doing',due:'30 jul'},
{id:2,title:'Recibir módulos 8 al 14',detail:'Solicitar y validar la versión documental oficial.',owner:'Christian',priority:'critical',status:'pending',due:'30 jul'},
{id:3,title:'Levantamiento de infraestructura',detail:'Croquis, áreas, equipos y evidencia fotográfica.',owner:'Operaciones',priority:'critical',status:'pending',due:'01 ago'},
{id:4,title:'Definir estructura organizacional',detail:'Responsables y funciones relacionadas con SRRC.',owner:'Dirección',priority:'high',status:'doing',due:'31 jul'},
{id:5,title:'Inventario de infraestructura',detail:'Listado maestro de instalaciones y equipos.',owner:'Mantenimiento',priority:'high',status:'pending',due:'02 ago'},
{id:6,title:'Análisis de peligros de infraestructura',detail:'Adecuar el análisis a las condiciones reales.',owner:'Calidad',priority:'critical',status:'pending',due:'03 ago'},
{id:7,title:'Programa de mantenimiento preventivo',detail:'Frecuencias, responsables y evidencias.',owner:'Mantenimiento',priority:'high',status:'pending',due:'04 ago'},
{id:8,title:'Procedimiento de mantenimiento',detail:'Revisión y adaptación a RED Greenhouse.',owner:'Calidad',priority:'high',status:'pending',due:'04 ago'},
{id:9,title:'Registro de hallazgos',detail:'Definir formato y mecanismo de seguimiento.',owner:'Calidad',priority:'medium',status:'pending',due:'05 ago'},
{id:10,title:'Macro y microlocalización',detail:'Preparar mapas de ubicación de la unidad.',owner:'Administración',priority:'high',status:'pending',due:'02 ago'},
{id:11,title:'Validar documentos del módulo 2',detail:'Revisar datos, firmas y control de versiones.',owner:'Christian',priority:'critical',status:'pending',due:'06 ago'},
{id:12,title:'Preparar impresión del módulo 2',detail:'Integrar documentos aprobados en carpeta física.',owner:'Administración',priority:'medium',status:'pending',due:'07 ago'}];
let tasks=JSON.parse(localStorage.getItem('redGreenhouseTasks')||'null')||defaultTasks;let activeFilter='all';
const statusLabels={pending:'Pendiente',doing:'En proceso',done:'Completada'};const priorityLabels={critical:'Crítica',high:'Alta',medium:'Media'};
function saveTasks(){localStorage.setItem('redGreenhouseTasks',JSON.stringify(tasks))}
function setDate(){document.getElementById('currentDate').textContent=new Intl.DateTimeFormat('es-MX',{day:'numeric',month:'long',year:'numeric'}).format(new Date());document.getElementById('daysRemaining').textContent=Math.max(0,Math.ceil((DEADLINE-new Date())/86400000))}
function progress(){if(!tasks.length)return 0;return Math.round(tasks.reduce((s,t)=>s+(t.status==='done'?1:t.status==='doing'?.5:0),0)/tasks.length*100)}
function esc(v=''){return v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function renderDashboard(){const p=progress();document.getElementById('progressValue').textContent=`${p}%`;document.getElementById('progressFill').style.width=`${p}%`;document.getElementById('dashboardTasks').innerHTML=tasks.slice(0,5).map(t=>`<div class="compact-task"><div><strong>${esc(t.title)}</strong><small>${esc(t.owner)} · ${esc(t.due)}</small></div><span class="badge badge-${t.priority}">${priorityLabels[t.priority]}</span><span class="badge status-badge">${statusLabels[t.status]}</span></div>`).join('')}
function renderTasks(){const f=tasks.filter(t=>activeFilter==='all'||(activeFilter==='critical'?t.priority==='critical':t.status===activeFilter));document.getElementById('taskList').innerHTML=f.length?f.map(t=>`<div class="task-row"><input class="task-check" type="checkbox" ${t.status==='done'?'checked':''} data-id="${t.id}"><div class="task-title"><strong>${esc(t.title)}</strong><small>${esc(t.detail||'')}</small></div><div class="task-owner">${esc(t.owner)}</div><span class="badge badge-${t.priority}">${priorityLabels[t.priority]}</span><div class="task-date">${esc(t.due||'Sin fecha')}</div><button class="delete-task" data-delete="${t.id}">×</button></div>`).join(''):'<div class="placeholder"><p>No hay tareas para este filtro.</p></div>';document.getElementById('totalTasks').textContent=tasks.length;document.getElementById('pendingTasks').textContent=tasks.filter(t=>t.status==='pending').length;document.getElementById('doingTasks').textContent=tasks.filter(t=>t.status==='doing').length;document.getElementById('doneTasks').textContent=tasks.filter(t=>t.status==='done').length;document.querySelectorAll('.task-check').forEach(i=>i.addEventListener('change',()=>{const t=tasks.find(x=>x.id===Number(i.dataset.id));if(t){t.status=i.checked?'done':'pending';saveTasks();renderAll()}}));document.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>{tasks=tasks.filter(t=>t.id!==Number(b.dataset.delete));saveTasks();renderAll()}))}
function renderAll(){renderDashboard();renderTasks()}
function showView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));const d=document.getElementById(`view-${v}`);if(d){d.classList.add('active');document.getElementById('breadcrumb').textContent=v==='inicio'?'Inicio':'Plan Maestro'}else{document.getElementById('view-placeholder').classList.add('active');document.getElementById('placeholderTitle').textContent=v.charAt(0).toUpperCase()+v.slice(1);document.getElementById('breadcrumb').textContent=v.charAt(0).toUpperCase()+v.slice(1)}document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===v));document.getElementById('sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.go)));document.getElementById('menuButton').addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTasks()}));
const modal=document.getElementById('modalBackdrop');document.getElementById('addTaskButton').addEventListener('click',()=>modal.classList.add('open'));document.getElementById('closeModal').addEventListener('click',()=>modal.classList.remove('open'));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});document.getElementById('taskForm').addEventListener('submit',e=>{e.preventDefault();tasks.unshift({id:Date.now(),title:document.getElementById('taskTitle').value.trim(),detail:'Tarea agregada desde el portal.',owner:document.getElementById('taskOwner').value.trim(),priority:document.getElementById('taskPriority').value,status:document.getElementById('taskStatus').value,due:'Sin fecha'});saveTasks();e.target.reset();modal.classList.remove('open');renderAll()});setDate();renderAll();
